name: Periodic Health Check

on:
  push:
    branches:
      - master

jobs:
  simple_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://desolate-coast-31906.herokuapp.com/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
